# Copyright 2025 Lincoln Institute of Land Policy
# SPDX-License-Identifier: MIT

server:
  bind:
    host: localhost #change to your hostname if running your own instance
    port: 5001
  url: ${PYGEOAPI_URL} #change to host URL if running your own instance
  mimetype: application/json; charset=UTF-8
  encoding: utf-8
  gzip: true
  language: en-US
  cors: true
  pretty_print: true
  limits:
    default_items: 500
    max_items: 10000
  map:
    url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
    attribution: '<a href="https://www.openstreetmap.org/copyright">© OpenStreetMap contributors</a>'

logging:
  level: ${PYGEOAPI_LOGLEVEL:-DEBUG}
  # logfile: /tmp/pygeoapi.log

metadata:
  identification:
    title: pygeoapi Postgres EDR
    description: Provides Postgres EDR via pygeaopi
    keywords:
      - EDR
      - pygeoapi
      - postgres
    keywords_type: theme
    terms_of_service: https://creativecommons.org/licenses/by/4.0/
    url: https://github.com/internetofwater/reference.geoconnex.us
  license:
    name: CC-BY 4.0 license
    url: https://creativecommons.org/licenses/by/4.0/
  provider:
    name: Center for Geospatial Solutions
    url: https://cgsearth.org/
  contact:
    address: 113 Brattle St
    city: Cambridge
    stateorprovince: Massachussetts
    postalcode: 02138
    country: USA
    email: internetofwater@lincolninst.edu
    url: https://internetofwater.org
    role: pointOfContact
    name: Benjamin Webb

resources:

  az_groundwater:
    type: collection
    title:
      en: Arizona Groundwater 
    description:
      en: Arizona Groundwater
    keywords:
      en:
        - example
        - quickstart
    extents:
      spatial:
        bbox: [-180, -90, 180, 90]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    providers:
      - type: feature
        name: PostgreSQL
        data:
          host: ${POSTGRES_HOST}
          dbname: ${POSTGRES_DB}
          user: ${POSTGRES_USER}
          password: ${POSTGRES_PASSWORD}
          search_path: [edr_quickstart]
        table: locations
        id_field: location_id
        geom_field: geometry

      - type: edr
        name: pgedr.PostgresEDRProvider
        data:
          host: ${POSTGRES_HOST}
          dbname: ${POSTGRES_DB}
          user: ${POSTGRES_USER}
          password: ${POSTGRES_PASSWORD}
          search_path: [edr_quickstart]
        table: observations
    
        edr_fields: # Required EDR Fields
          id_field: observation_id
          location_field: locations.location_id
          geom_field: locations.geometry # Result geometry field
          time_field: observation_time
          result_field: observation_value
          parameter_id: parameters.parameter_id
          parameter_name: parameters.parameter_name
          parameter_unit: parameters.parameter_unit_symbol

        external_tables: # Additional table joins
          locations:
            remote: location_id
            foreign: location_id
          parameters:
            remote: parameter_id
            foreign: parameter_id